# Generated by Django 4.1.1 on 2022-10-02 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banket.seat'),
        ),
    ]
