# Generated by Django 4.1.1 on 2022-10-03 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banket', '0003_image_hole_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hole',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='hole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banket.hole'),
        ),
    ]
