# Generated by Django 4.1.1 on 2022-10-04 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banket', '0004_remove_hole_images_image_hole'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereddish',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_type',
            field=models.CharField(choices=[('COLD', 'Cold'), ('WARM', 'Warm'), ('SNACK', 'Snack'), ('SALAD', 'Salad'), ('DRINK', 'Drink')], max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('1', 'Birthday'), ('2', 'Wedding'), ('3', 'Сhristening'), ('4', 'Other')], max_length=255),
        ),
    ]
