# Generated by Django 4.1.1 on 2022-10-07 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banket', '0005_ordereddish_user_alter_dish_dish_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='description',
            field=models.TextField(default='Hole'),
        ),
        migrations.AlterField(
            model_name='image',
            name='hole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='banket.hole'),
        ),
    ]
